#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

# exec git update-server-info

unset GIT_DIR

NowPath=`pwd`

DeployPath="/var/www/html"

cd $DeployPath
git pull origin master
# npm install
# composer install

cd $NowPath

echo 'deploy success'
exit 0


